export async function test(ctx, next) {
	try {
		console.log('YEEEEEEEE Success');
	} catch (ex) {
		console.log('xiaoyangNew1Landing error', ex);
	}
}